### ISSUE TITLE
RuntimeError: Digest::Base cannot be directly inherited in Ruby

### ISSUE THREAD

**Issue by mcoetzee** [ahoward/sekrets#14]
Alright so we are sporadically getting this `RuntimeError` in our Sidekiq workers and the offending line of code is [lib/sekrets.rb#L303](https://github.com/ahoward/sekrets/blob/master/lib/sekrets.rb#L303):
```rb
cipher.key = Digest::SHA256.digest(key.to_s).slice(0,16)
```

After some digging I found a similar issue in the `aerospike-client-ruby` gem:
[Digest::Base cannot be directly inherited in Ruby](https://github.com/aerospike/aerospike-client-ruby/issues/45)

Which they solved by using the [thread-safe digest lookup](https://github.com/aerospike/aerospike-client-ruby/pull/50/files).

Would you agree that this line [lib/sekrets.rb#L303](https://github.com/ahoward/sekrets/blob/master/lib/sekrets.rb#L303) should similarly be changed to use the thread-safe digest lookup?

**Comment by ahoward** [comment]
better late that never but on master now
