### ISSUE TITLE
It's not working with ruby 2.4.0 and Rails 5.0.2

### ISSUE THREAD

**Issue by JohnSmall** [ahoward/sekrets#8]
In Ubuntu 14.04, Ruby 2.4.0 and Rails 5.0.2

Following the instructions for rails I created a key then got to the next line
`rake sekrets:generate:editor`

And got this error

`path_removed/gems/sekrets-1.9.1/lib/sekrets.rb:295: warning: constant OpenSSL::Cipher::Cipher is deprecated
rake aborted!
ArgumentError: key must be 16 bytes
`

So how do I use this gem?

**Comment by copiousfreetime** [comment]
@JohnSmall pull request #9 will solve this, hoping to have @ahoward drop it in today/tomorrow

**Comment by copiousfreetime** [comment]
@JohnSmall Version 1.10.0 was released to rubygems. So you should be good to go. Please let us know if you have any problems.
